# Generated by Django 4.2.4 on 2023-08-16 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airlines", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"verbose_name_plural": "crew"},
        ),
        migrations.RemoveField(
            model_name="route",
            name="distance",
        ),
    ]
