# Generated by Django 4.2.4 on 2023-08-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airlines", "0002_alter_crew_options_remove_route_distance"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="number",
            field=models.CharField(default="12-A-3D", max_length=10),
        ),
    ]
