# Generated by Django 4.2.4 on 2023-08-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airlines", "0004_airplane_image_airport_image_crew_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="close_big_city",
            field=models.CharField(max_length=255),
        ),
    ]
