# Generated by Django 4.2.4 on 2023-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airlines", "0005_alter_airport_close_big_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
